-- add inventory schema

-- Auto-update updatedAt on row changes.
create or replace function touchUpdatedAt()
returns trigger
language plpgsql
as $$
begin
  new.updatedAt = now();
  return new;
end;
$$;

-- A timestamp as the browser's wire form for a Date, or null.
create or replace function jsDate(t timestamptz)
returns json
language sql
immutable
as $$
  select case
    when t is null then null
    else json_build_object('$type', 'Date', '$value', (extract(epoch from t) * 1000)::bigint)
  end;
$$;

create type userRole as enum ('manager', 'staff');
create type movementReason as enum ('count', 'damage', 'sale', 'receipt');
create type poStatus as enum ('draft', 'sent', 'partially_received', 'received');

create table users (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  email text not null unique,
  name text not null,
  passwordHash text not null,
  role userRole not null default 'staff'
);

create trigger usersTouchUpdatedAt
  before update on users
  for each row execute function touchUpdatedAt();

create table suppliers (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  name text not null unique,
  contactName text not null default '',
  email text not null
);

create trigger suppliersTouchUpdatedAt
  before update on suppliers
  for each row execute function touchUpdatedAt();

create table products (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  sku text not null unique,
  name text not null,
  supplierId uuid not null references suppliers (id),
  costCents integer not null check (costCents >= 0),
  onHand integer not null default 0 check (onHand >= 0),
  reorderPoint integer not null default 0 check (reorderPoint >= 0)
);

create index productsSupplierIdIdx on products (supplierId);

create trigger productsTouchUpdatedAt
  before update on products
  for each row execute function touchUpdatedAt();

create table stockMovements (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  productId uuid not null references products (id) on delete cascade,
  delta integer not null,
  quantityAfter integer not null,
  reason movementReason not null,
  note text not null default '',
  userName text not null,
  purchaseOrderId uuid
);

create index stockMovementsProductIdx on stockMovements (productId, createdAt desc);

create trigger stockMovementsTouchUpdatedAt
  before update on stockMovements
  for each row execute function touchUpdatedAt();

create table purchaseOrders (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  number integer not null unique generated by default as identity (start with 1001),
  supplierId uuid not null references suppliers (id),
  status poStatus not null default 'draft',
  createdByName text not null,
  sentAt timestamptz,
  receivedAt timestamptz
);

create index purchaseOrdersStatusIdx on purchaseOrders (status);

create trigger purchaseOrdersTouchUpdatedAt
  before update on purchaseOrders
  for each row execute function touchUpdatedAt();

create table poLines (
  id uuid primary key default uuidGenerateV7(),
  createdAt timestamptz not null default now(),
  updatedAt timestamptz not null default now(),
  purchaseOrderId uuid not null references purchaseOrders (id) on delete cascade,
  productId uuid not null references products (id),
  quantityOrdered integer not null check (quantityOrdered > 0),
  quantityReceived integer not null default 0 check (quantityReceived >= 0),
  unitCostCents integer not null check (unitCostCents >= 0),
  unique (purchaseOrderId, productId),
  check (quantityReceived <= quantityOrdered)
);

create trigger poLinesTouchUpdatedAt
  before update on poLines
  for each row execute function touchUpdatedAt();

-- ---------------------------------------------------------------------------
-- Row shapes. The LiveTable selects read these, and the notify triggers send
-- them, so a page sees the same row whether it loaded it or heard about it.
-- ---------------------------------------------------------------------------

create or replace function productRow(pid uuid)
returns json
language sql
stable
as $$
  select json_build_object(
    'id', p.id,
    'sku', p.sku,
    'name', p.name,
    'supplierId', p.supplierId,
    'supplierName', s.name,
    'costCents', p.costCents,
    'onHand', p.onHand,
    'reorderPoint', p.reorderPoint,
    'updatedAt', jsDate(p.updatedAt)
  )
  from products p
  join suppliers s on s.id = p.supplierId
  where p.id = pid;
$$;

create or replace function purchaseOrderRow(poid uuid)
returns json
language sql
stable
as $$
  select json_build_object(
    'id', po.id,
    'number', po.number,
    'supplierId', po.supplierId,
    'supplierName', s.name,
    'supplierEmail', s.email,
    'status', po.status,
    'createdByName', po.createdByName,
    'createdAt', jsDate(po.createdAt),
    'sentAt', jsDate(po.sentAt),
    'receivedAt', jsDate(po.receivedAt),
    'lineCount', coalesce(l.lineCount, 0),
    'unitsOrdered', coalesce(l.unitsOrdered, 0),
    'unitsReceived', coalesce(l.unitsReceived, 0),
    'totalCents', coalesce(l.totalCents, 0)
  )
  from purchaseOrders po
  join suppliers s on s.id = po.supplierId
  left join lateral (
    select
      count(*)::int as lineCount,
      sum(quantityOrdered)::int as unitsOrdered,
      sum(quantityReceived)::int as unitsReceived,
      sum(quantityOrdered * unitCostCents)::int as totalCents
    from poLines
    where purchaseOrderId = po.id
  ) l on true
  where po.id = poid;
$$;

create or replace function poLineRow(lid uuid)
returns json
language sql
stable
as $$
  select json_build_object(
    'id', l.id,
    'purchaseOrderId', l.purchaseOrderId,
    'productId', l.productId,
    'sku', p.sku,
    'name', p.name,
    'quantityOrdered', l.quantityOrdered,
    'quantityReceived', l.quantityReceived,
    'unitCostCents', l.unitCostCents,
    'createdAt', jsDate(l.createdAt)
  )
  from poLines l
  join products p on p.id = l.productId
  where l.id = lid;
$$;

create or replace function stockMovementRow(mid uuid)
returns json
language sql
stable
as $$
  select json_build_object(
    'id', m.id,
    'productId', m.productId,
    'delta', m.delta,
    'quantityAfter', m.quantityAfter,
    'reason', m.reason,
    'note', m.note,
    'userName', m.userName,
    'purchaseOrderId', m.purchaseOrderId,
    'purchaseOrderNumber', po.number,
    'createdAt', jsDate(m.createdAt)
  )
  from stockMovements m
  left join purchaseOrders po on po.id = m.purchaseOrderId
  where m.id = mid;
$$;

-- ---------------------------------------------------------------------------
-- Live broadcasts. Every write, from an rpc, a job or psql, reaches open pages.
-- ---------------------------------------------------------------------------

create or replace function liveNotify(channel text, op text, id uuid, data json)
returns void
language plpgsql
as $$
declare
  payload text;
begin
  if op = 'delete' or data is null then
    payload := json_build_object('op', 'delete', 'data', json_build_object('id', id))::text;
  else
    payload := json_build_object('op', op, 'data', data)::text;
  end if;

  if octet_length(payload) >= 8000 then
    payload := json_build_object('op', op, 'id', id)::text;
  end if;

  perform pg_notify(channel_name(channel), payload);
end;
$$;

create or replace function productsNotify()
returns trigger
language plpgsql
as $$
declare
  r record;
  op text := lower(tg_op);
  data json;
begin
  r := coalesce(new, old);

  if op <> 'delete' then
    data := productRow(r.id);
  end if;

  perform liveNotify('products', op, r.id, data);

  return r;
end;
$$;

create trigger productsNotifyTrigger
  after insert or update or delete on products
  for each row execute function productsNotify();

create or replace function suppliersNotify()
returns trigger
language plpgsql
as $$
declare
  p record;
  op text := lower(tg_op);
  data json;
begin
  if op = 'update' then
    for p in select id from products where supplierId = new.id loop
      data := productRow(p.id);
      perform liveNotify('products', 'update', p.id, data);
    end loop;
  end if;

  return coalesce(new, old);
end;
$$;

create trigger suppliersNotifyTrigger
  after update on suppliers
  for each row execute function suppliersNotify();

create or replace function stockMovementsNotify()
returns trigger
language plpgsql
as $$
declare
  r record;
  op text := lower(tg_op);
  data json;
begin
  r := coalesce(new, old);

  if op <> 'delete' then
    data := stockMovementRow(r.id);
  end if;

  perform liveNotify('stock_movements', op, r.id, data);

  return r;
end;
$$;

create trigger stockMovementsNotifyTrigger
  after insert or update or delete on stockMovements
  for each row execute function stockMovementsNotify();

create or replace function notifyPurchaseOrder(poid uuid, op text)
returns void
language plpgsql
as $$
declare
  data json;
begin
  if op <> 'delete' then
    data := purchaseOrderRow(poid);

    -- A line deleted by the cascade of its order's delete finds no order.
    if data is null then
      return;
    end if;
  end if;

  perform liveNotify('purchase_orders', op, poid, data);
end;
$$;

create or replace function purchaseOrdersNotify()
returns trigger
language plpgsql
as $$
declare
  r record;
begin
  r := coalesce(new, old);
  perform notifyPurchaseOrder(r.id, lower(tg_op));

  return r;
end;
$$;

create trigger purchaseOrdersNotifyTrigger
  after insert or update or delete on purchaseOrders
  for each row execute function purchaseOrdersNotify();

create or replace function poLinesNotify()
returns trigger
language plpgsql
as $$
declare
  r record;
  op text := lower(tg_op);
  data json;
begin
  r := coalesce(new, old);

  if op <> 'delete' then
    data := poLineRow(r.id);
  end if;

  perform liveNotify('po_lines', op, r.id, data);

  -- The order's totals move with its lines.
  perform notifyPurchaseOrder(r.purchaseOrderId, 'update');

  return r;
end;
$$;

create trigger poLinesNotifyTrigger
  after insert or update or delete on poLines
  for each row execute function poLinesNotify();
